# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egresados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_captura', models.DateField()),
                ('aporte', models.CharField(max_length=200)),
                ('medio_difusion_captado', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('PERIODICO', 'Periodico'), ('TV', 'Tv'), ('RADIO', 'Radio'), ('ESCUELA', 'Escuela'), ('AMIGO', 'Amigo'), ('EMPRESA', 'Empresa'), ('OTRO', 'Otro medio')], max_length=20, verbose_name='Como te enteraste del programa')),
                ('activ_perfil', models.BooleanField()),
                ('medios_necesarios', models.BooleanField()),
                ('capacitacion', models.BooleanField()),
                ('apoyo_extra', models.BooleanField()),
                ('contratado', models.BooleanField()),
                ('razon_no_contratado', models.CharField(max_length=200)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.FloatField()),
                ('prog_logro_espect', models.BooleanField()),
                ('mejora_programa', models.CharField(max_length=400)),
                ('mejora_empresa', models.CharField(max_length=400)),
                ('mejora_institucion', models.CharField(max_length=400)),
                ('cubrieron_necesidades', models.BooleanField()),
                ('porque_no_necesidades', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='reporteMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('area', models.CharField(max_length=200)),
                ('tutor', models.CharField(max_length=200)),
                ('actividades', models.CharField(max_length=200)),
                ('aporte', models.CharField(max_length=200)),
                ('monto', models.CharField(max_length=200)),
                ('proyecto', models.CharField(max_length=200)),
                ('puntualidad', models.CharField(max_length=200)),
                ('capacitacion', models.CharField(max_length=200)),
                ('recursos', models.BooleanField()),
                ('experiencia', models.BooleanField()),
                ('emp_puntualidad', models.BooleanField()),
                ('emp_imagen', models.BooleanField()),
                ('emp_actitud', models.BooleanField()),
                ('emp_aprendio', models.BooleanField()),
                ('emp_objetivos_cump', models.BooleanField()),
                ('validado', models.BooleanField()),
                ('fecha_validacion', models.DateField()),
                ('pago', models.BooleanField()),
                ('fecha_pago', models.DateField()),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egresados.Egresado')),
            ],
        ),
        migrations.CreateModel(
            name='sedeco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('acceso', models.IntegerField()),
                ('rol', models.IntegerField()),
                ('activate', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='sedeco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.sedeco'),
        ),
    ]
