# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egresados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('area', models.CharField(max_length=100)),
                ('tutor', models.CharField(max_length=200)),
                ('actividades', models.CharField(max_length=400)),
                ('aporte', models.CharField(max_length=100)),
                ('monto', models.CharField(max_length=10)),
                ('capacitacion', models.BooleanField()),
                ('en_que', models.BooleanField()),
                ('proyecto', models.CharField(max_length=200)),
                ('recursos', models.BooleanField()),
                ('experiencia', models.BooleanField()),
                ('emp_puntualidad', models.BooleanField()),
                ('emp_imagen', models.BooleanField()),
                ('emp_actitud', models.BooleanField()),
                ('emp_aprendio', models.BooleanField()),
                ('emp_objetivos_cump', models.BooleanField()),
                ('validado', models.BooleanField()),
                ('fecha_validacion', models.DateField()),
                ('pago', models.BooleanField()),
                ('fecha_pago', models.DateField()),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='egresados.Egresado')),
            ],
        ),
    ]
