# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('sectores', models.CharField(max_length=20)),
                ('validada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidop', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidom', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.IntegerField()),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaentregatitulo', models.DateField(auto_now_add=True, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('telefonofijo', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estudioen', models.CharField(blank=True, max_length=100, null=True)),
                ('añoegreso', models.DateField(auto_now_add=True, null=True)),
                ('fechaingresoprograma', models.DateField(auto_now_add=True, null=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificado')),
                ('identificacion', models.FileField(blank=True, null=True, upload_to='identificación')),
                ('compdomicilio', models.FileField(blank=True, null=True, upload_to='domicilio')),
                ('titulo', models.FileField(blank=True, null=True, upload_to='titulo')),
                ('fcurp', models.FileField(blank=True, null=True, upload_to='curp')),
                ('carta', models.FileField(blank=True, null=True, upload_to='carta')),
                ('fechatitulacion', models.DateField(auto_now_add=True, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('becario', models.BooleanField(default=False, verbose_name='Es Becario')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='cv')),
                ('archivopsicologica', models.FileField(blank=True, null=True, upload_to='psico')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='egresados.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='EstSocioEcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edo_civil', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50)),
                ('dependientes', models.CharField(max_length=2)),
                ('situacionlaboral', models.CharField(max_length=20)),
                ('trabajo', models.CharField(max_length=30)),
                ('dependen_ti', models.BooleanField(verbose_name='Alguien depende de ti?')),
                ('cuantos_depend', models.IntegerField(verbose_name='Cuantos dependen de ti')),
                ('ingreso_mensual', models.CharField(max_length=20)),
                ('transporte', models.BooleanField()),
                ('vives_en', models.CharField(max_length=60)),
                ('cuantos_hermanos', models.CharField(max_length=20)),
                ('cuantos_papas', models.CharField(max_length=20)),
                ('cuantos_abuelos', models.CharField(max_length=20)),
                ('casa_techo', models.CharField(max_length=20)),
                ('casa_piso', models.CharField(max_length=20)),
                ('casa_pared', models.CharField(max_length=20)),
                ('numero_banos', models.IntegerField()),
                ('numero_salas', models.IntegerField()),
                ('numero_comedor', models.CharField(max_length=20)),
                ('numero_vehiculos', models.IntegerField()),
                ('numero_recamaras', models.IntegerField()),
                ('gasto_mensual', models.CharField(max_length=20)),
                ('mayor_gasto', models.CharField(max_length=20)),
                ('otra_beca', models.BooleanField()),
                ('id_egresado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='egresados.Egresado')),
            ],
        ),
        migrations.CreateModel(
            name='Expectativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrevista_lab', models.BooleanField()),
                ('que_quieres', models.CharField(max_length=100)),
                ('que_esperas', models.CharField(max_length=100)),
                ('uso_beca', models.CharField(max_length=100, verbose_name='Que haras con la beca?')),
                ('aportacion', models.TextField(max_length=100)),
                ('logro', models.TextField(max_length=100, verbose_name='Objetivo Profesional')),
                ('logro_academico', models.CharField(max_length=100, verbose_name='Objetivo Academico')),
                ('formacion', models.CharField(max_length=20, verbose_name='Objetivo Academico')),
                ('eleccion_correcta', models.BooleanField()),
                ('gasto_mensual', models.CharField(max_length=80)),
                ('empleo_buscado', models.BooleanField(verbose_name='Buscaste empleo')),
                ('tiempo_busqueda', models.CharField(max_length=80, verbose_name='Cuanto tiempo')),
                ('medios_busqueda', models.CharField(max_length=80, verbose_name='Que medios usaste para buscar')),
                ('id_egresado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='egresados.Egresado')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('empresa', models.CharField(max_length=100)),
                ('actividades', models.TextField()),
                ('id_egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egresados.Egresado')),
            ],
        ),
    ]
